users:
  - username: lukas.nagy
    name: Lukas Nagy
    uid: 1001
    home: /data/home/lukas.nagy
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIsy1exxUVNL4doHL7qOZ6s28zCqeiPxjDh9q/16uezL43Rx2FMJ709GsZHItEE3f65wgH/5DGMUx1M7CZLBOs6BvkWp6uF22NYR/vO5Saq20MpuAn0/R7NuQpebZrCDWzN0pTFeh9C1LZxva3Aa+iaSwQC8Wtw17Dcq8R4y3D7A8iLpriueXTvYRfJ6/MfwHxIg1BnrPlA1h/gNX3N/vTpaX4hGa/zy1v9HiJw2oiYrf1Q+NTgVZYKQtlG6X8txEeFS964oBM0mIjr7ZTupBopKyqkjWt1NT+uqJjhp7wP4W5YmBfAJijOTRUSfS/D4Xn79OBaIOuAX0WihDd6Bph lukas.nagy@gnsystems.sk"
    password: "{{ vault_lukas_nagy_password | password_hash('sha512') }}"
    samba_user: yes
  - username: kristyna.ruzickova
    name: Kristyna Ruzickova
    uid: 1002
    home: /data/home/kristyna.ruzickova
    shell: /sbin/nologin
    password: "{{ vault_kristyna_ruzickova_password | password_hash('sha512') }}"
    samba_user: yes
  - username: backup_user
    name: Borg Backup user
    uid: 1003
    home: /data/home/backup
    shell: /bin/bash
    password: "{{ vault_backup_user_password | password_hash('sha512')}}"
    samba_user: no
