- hosts: homenas
  
  tasks:
    - name: Set up SELinux context for different default SSH home (for SSH)
      sefcontext:
        target: '/data/home/[^/]+/\.ssh(/.*)?'
        setype: ssh_home_t
        state: present

    - name: Apply new SELinux file context to filesystem
      command: restorecon -irv /data/home/
  
  roles:
    - role: singleplatform-eng.users
      vars: 
        - ansible_become: true
    - role: geerlingguy.firewall
    - role: bertvv.samba
    - role: samba-standalone
    - role: borgbackup-central-repository
#    - cloudalchemy.coredns
